export function isConsoleCardActivationKey(key: string) {
  return key === 'Enter' || key === ' '
}

/**
 * Native pointer clicks have a positive detail count. A zero-detail click is
 * the synthetic click generated by keyboard/gamepad activation, so it is the
 * only click event allowed to launch the selected game.
 */
export function shouldActivateConsoleCardClick(detail: number) {
  return detail === 0
}
